"""Add country and eligibility fields

Revision ID: add_country_eligibility
Revises: 389215b5d97d
Create Date: 2026-05-16 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_country_eligibility'
down_revision = '389215b5d97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seekers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('age_verified', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('legally_eligible', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('age_verified', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('legally_eligible', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employers', schema=None) as batch_op:
        batch_op.drop_column('legally_eligible')
        batch_op.drop_column('age_verified')
        batch_op.drop_column('country')

    with op.batch_alter_table('seekers', schema=None) as batch_op:
        batch_op.drop_column('legally_eligible')
        batch_op.drop_column('age_verified')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
